In [1]:
import pandas as pd
import numpy as np

# Numpy exercise for practice

## Easy section

### 3. Create a null vector of size 10 

In [2]:
null_vect = np.array([None]).repeat(10)
null_vect

array([None, None, None, None, None, None, None, None, None, None],
      dtype=object)

In [3]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 4. How to find the memory size of any array

In [4]:
zeros.__sizeof__()

192

### 5. How to get the documentation of the numpy add function from the command line 

In [5]:
print(np.add.__doc__)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [6]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

### 6. Create a null vector of size 10 but the fifth value which is 1

In [7]:
nulls = np.zeros(10)
nulls[4] = 1
nulls

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### 7. Create a vector with values ranging from 10 to 49

In [8]:
values = np.arange(10,50)
values

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 8. Reverse a vector (first element becomes last)

In [9]:
values[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
three = np.arange(1,10).reshape((3,3))
three

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 10. Find indices of non zero elements from [1,2,0,0,4,0]

In [11]:
arr = np.array([1,2,0,0,4,0])
locations = np.where(arr != 0)
locations

(array([0, 1, 4], dtype=int64),)

In [12]:
indices = np.nonzero(arr)
indices

(array([0, 1, 4], dtype=int64),)

### 11. Create a 3x3 indentity matrix

In [13]:
identity = np.zeros(9).reshape(3,3)
identity

identity[0][0] = 1
identity[1][1] = 1
identity[2][2] = 1

identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 12. Create a 3x3x3 array with random values

In [16]:
rands = np.random.random((3,3,3))
rands

array([[[0.95014302, 0.87499416, 0.51278162],
        [0.76414659, 0.67059215, 0.46178679],
        [0.21940849, 0.43667563, 0.47338207]],

       [[0.89856719, 0.36902475, 0.24267596],
        [0.05442408, 0.70879392, 0.62890906],
        [0.89199155, 0.3398985 , 0.35518709]],

       [[0.03299452, 0.75434082, 0.92453684],
        [0.71736283, 0.55476339, 0.26544153],
        [0.18680085, 0.07859465, 0.88812988]]])

### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [17]:
np.random.seed(42)

randint = np.random.randint(0,50,(10,10))
randint

array([[38, 28, 14, 42,  7, 20, 38, 18, 22, 10],
       [10, 23, 35, 39, 23,  2, 21,  1, 23, 43],
       [29, 37,  1, 20, 32, 11, 21, 43, 24, 48],
       [26, 41, 27, 15, 14, 46, 43,  2, 36,  6],
       [20,  8, 38, 17,  3, 24, 13, 49,  8, 25],
       [ 1, 19, 27, 46,  6, 43,  7, 46, 34, 13],
       [16, 35, 49, 39,  3,  1,  5, 41,  3, 28],
       [17, 25, 43, 33,  9, 35, 13, 30, 47, 14],
       [ 7, 13, 22, 39, 20, 15, 44, 17, 46, 23],
       [25, 24, 44, 40, 28, 14, 44,  0, 24,  6]])

### 14. Create a random vector of size 30 and find the mean value

In [18]:
np.random.seed(42)

vect30 = np.random.randint(0,100,(1,30))
vect30.mean()

50.86666666666667

In [19]:
arr30 = np.random.random(30)

arr30.mean()

0.46437854199164835

### 15. Create a 2d array with 1 on the border and 0 inside

In [20]:
arr2d = np.ones(16).reshape(4,4)
print(arr2d)

arr2d[1,1] = 0
arr2d[1,2] = 0
arr2d[2,1] = 0
arr2d[2,2] = 0

print(arr2d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [21]:
arrones2d = np.ones((3,3))
arrones2d[1,1] = 0
arrones2d

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

In [22]:
size = int(input("what is going to be the size of your array: "))
ones = np.ones((size,size))
zeros = np.zeros((size-2,size-2))

ones[1:ones.shape[0]-1,1:ones.shape[1]-1] = zeros

ones

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [23]:
dim = int(input("Please what will be the dimension of your array: "))

Z = np.ones((dim,dim))
Z[1:-1,1:-1] = 0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

### 16. How to add a border (filled with 0's) around an existing array? 

In [24]:
border_zeros = np.arange(1,17).reshape(4,4)
border_zeros

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [25]:
arr = np.array([1,2,3])

zeros = np.zeros((3,len(arr) + 2))
print(zeros)

zeros[1,1:-1] = arr
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 0.]
 [0. 0. 0. 0. 0.]]


In [26]:
dimn = int(input("PLease give us the dimension of your array: "))

z = np.random.randint(1,50,(dimn,dimn))
z = np.pad(z,pad_width=1,mode='constant',constant_values=0)
z

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0, 29, 18, 26, 44, 34,  0],
       [ 0, 10, 36, 14, 31, 48,  0],
       [ 0, 15,  8, 14, 23, 40,  0],
       [ 0, 21, 16, 45, 18, 47,  0],
       [ 0, 24, 26, 25, 45, 41,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

### 17. What is the result of the following expression?
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [27]:
'''
np.nan
False
True
np.nan
False
False
'''

'\nnp.nan\nFalse\nTrue\nnp.nan\nFalse\nFalse\n'

In [28]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == (3 * 0.1))

nan
False
False
nan
True
False


### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [29]:
# matrix = np.random.randint(1,20,(5,5))
matrix = np.zeros((5,5))
print(matrix)

matrix[1,0] = 1
matrix[2,1] = 2
matrix[3,2] = 3
matrix[4,3] = 4

print("\n")

print(matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [30]:
diag = np.zeros((5,5))
arr = np.arange(1,5)

diag[arr,arr-1] = arr

diag

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

In [31]:
sized = int(input("What is the size: "))

diags = np.diag(1+np.arange(sized),k=-1)
diags

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0]])

### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [32]:
checkerboard = np.zeros((8,8))
# np.where(checkerboard.shape().sum() % 2 == 1, 1, checkerboard)
checkerboard[::2, 1::2] = 1 # getting the eventh element of the oddth row
checkerboard[1::2, ::2] = 1 # getting the oddth element of the eventh row
checkerboard

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [33]:
large = np.arange(1,337).reshape(6,7,8)
large[1,5,3]

100

In [34]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

### 21. Create a checkerboard 8x8 matrix using the tile function

In [35]:
arr_tile = np.array([0,1])
# np.tile(arr_tile,32).reshape((8,8))

odd_row = np.tile(arr_tile,4)
even_row = np.tile(arr_tile[::-1],4)

# print("\n",odd_row,"\n",even_row)

np.tile(np.hstack((odd_row,even_row)),4).reshape((8,8))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### 22. Normalize a 5x5 random matrix

In [36]:
np.random.seed(42)

norm = np.random.randint(1,25,(5,5))
norm

(norm - norm.mean()) / norm.std()

array([[-0.89520217,  0.79631356,  0.14573059, -0.37473579, -0.76508558],
       [ 0.92643016, -0.89520217,  0.66619697,  1.18666335, -0.37473579],
       [-0.37473579,  1.31677994,  0.92643016, -1.28555196, -0.76508558],
       [ 1.31677994, -1.41566855,  1.05654675,  0.92643016, -1.54578515],
       [ 1.31677994, -0.2446192 , -1.02531877, -1.54578515,  0.92643016]])

### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [37]:
RGBA = np.dtype('u4')

RGBA

dtype('uint32')

In [38]:
color = np.dtype(
  [
    ("r", np.ubyte),
    ("g", np.ubyte),
    ("b", np.ubyte),
    ("a", np.ubyte),
  ]
)

color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

### 24 Multiple a 5x3 matrix bu a 3x2 matrix (real matrix product)

In [39]:
np.random.seed(42)

mat53 = np.random.randint(4,12,(5,3))
mat32 = np.random.randint(3,14,(3,2))

print("\n",mat53,"\n",mat32)

result = np.matmul(mat53,mat32)
result


 [[10  7  8]
 [10  6 11]
 [ 8  8 10]
 [ 5  6 10]
 [ 6  6 11]] 
 [[ 7  6]
 [10 10]
 [ 5  8]]


array([[180, 194],
       [185, 208],
       [186, 208],
       [145, 170],
       [157, 184]])

In [40]:
Y = np.dot(mat53,mat32)
Y

array([[180, 194],
       [185, 208],
       [186, 208],
       [145, 170],
       [157, 184]])

### 25. Given a 1D array, negate all elements which are between 3 and 8, in place

In [41]:
# np.random.randint(42)

neg = np.random.randint(1,15,(1,12))
neg = np.where((neg>=3) & (neg<=8),neg*-1,neg)
neg

array([[-5,  2, -8, 12, 14, -6,  2, 12, -5,  1, 12, 10]])

In [42]:
# np.random.randint(42)

neg1 = np.random.randint(1,15,(1,12))
neg1 = np.where((neg1>=3) & (neg1<=8),neg1.__neg__(),neg1)
neg1

array([[-6, 13, 12,  9,  1, 11, 11, 10, 12, 12, 14, 14]])

### 26. What is the output of the following script?
```python
# Author: 

print(sum(rnage(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [43]:
# 10
# 10

In [44]:
print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))

9
10


### 27. Consider an integer vector Z, which of these expressions are legal?

```python
w**w
w << w >> 2
w <- w
1j*w
w/1/1
w<w>w
```

In [45]:
# Legal
# Legal
# Not Legal
# Legal
# Legal
# Not Legal

In [47]:
np.random.seed()

w = np.random.randint(0,10,5)

print(w)
 
print(w**w,"\n1")
print(w << w >> 2,"\n2")
print(w < -w,"\n3")
print(1j * w,"\n4")
print(w / 1 / 1,"\n5")
# print(w < w > w,"\n6")

[7 7 6 1 7]
[823543 823543  46656      1 823543] 
1
[224 224  96   0 224] 
2
[False False False False False] 
3
[0.+7.j 0.+7.j 0.+6.j 0.+1.j 0.+7.j] 
4
[7. 7. 6. 1. 7.] 
5


### 28. What are the results of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [48]:
# nan
# 0.0
# nan

In [49]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

C:\Users\TabotCharlesBessong\AppData\Local\Temp\ipykernel_8748\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\TabotCharlesBessong\AppData\Local\Temp\ipykernel_8748\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


nan
0
[-2.14748365e+09]


C:\Users\TabotCharlesBessong\AppData\Local\Temp\ipykernel_8748\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


### 29. How to round away from zero a float array?

In [50]:
float= np.random.random(5)
print(float)
print(np.ceil(float))

[0.86071912 0.79810588 0.63438986 0.62559799 0.32601671]
[1. 1. 1. 1. 1.]


In [51]:
V = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(V)),V))

[  5.  -6.  -2. -10.  -5.  -6.  -7.   1.   4.  -2.]


In [52]:
print(np.where(V>0,np.ceil(V),np.floor(V)))

[  5.  -6.  -2. -10.  -5.  -6.  -7.   1.   4.  -2.]


### 30. How to find common values between two arrays?

In [53]:
a = np.arange(0,10)
b= np.arange(3,12)

np.intersect1d(a,b)

array([3, 4, 5, 6, 7, 8, 9])

### 31. How to ignore all numpy warnings (not recommended)?

In [54]:
# suicide mode on
# errors = np.seterr(all="ignore")

U = np.ones(1) / 0
U

C:\Users\TabotCharlesBessong\AppData\Local\Temp\ipykernel_8748\1615916133.py:4: RuntimeWarning: divide by zero encountered in divide
  U = np.ones(1) / 0


array([inf])

In [55]:
# back to sanity
# san = np.seterr(**defaults)

### 32. Is the following expressions true?

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [56]:
# False

In [57]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\TabotCharlesBessong\AppData\Local\Temp\ipykernel_8748\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

### 33. How to get the dates of yesterday, today and tomorrow?

In [58]:
from datetime import datetime, timedelta

today = datetime.now()
print(today)

yesterday = today - timedelta(days=1)
print(yesterday)

tomorrow = today + timedelta(days=1)
print(tomorrow)

2024-11-22 04:23:27.950492
2024-11-21 04:23:27.950492
2024-11-23 04:23:27.950492


In [59]:
aujourdhui = np.datetime64('today')
hier = aujourdhui - np.timedelta64(1,'D')
demain = aujourdhui + np.timedelta64(1,'D')

print(f"Today's date: {today}\nYestersday's Date is: {hier}\nTomorrow's date is: {demain}")

Today's date: 2024-11-22 04:23:27.950492
Yestersday's Date is: 2024-11-21
Tomorrow's date is: 2024-11-23


In [60]:
lobii = np.datetime64('today') - np.timedelta64(1)
lelo = np.datetime64('today')
lobi = np.datetime64('today') + np.timedelta64(1)

print(
  f"Yesterday's Date is: {lobii}\nToday's Date is: {lelo}\nTomorrow's Date is: {lobi}"
)

Yesterday's Date is: 2024-11-21
Today's Date is: 2024-11-22
Tomorrow's Date is: 2024-11-23


### 34. How to get all the dates corresponding to the month of July 2016?

In [61]:
july2016 = np.datetime64("2016-07")
np.arange(np.datetime64('2016-07-01'),np.datetime64('2016-08-01'))

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [62]:
T = np.arange('2016-07','2016-08',dtype='datetime64[D]')
T

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')