In [1]:
import pandas as pd
import numpy as np

The history saving thread hit an unexpected error (OperationalError('database is locked')).History will not be written to the database.


# Numpy Exercise for practice

## Medium section

### 35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [2]:
A = np.array([1,2,3,4])
B = np.array([1,1,1,1])

C = np.multiply((np.add(A,B)),(np.negative(A)/2))
C

array([ -1.,  -3.,  -6., -10.])

### 36. Extract the integer part of a random array of positive numbers using 4 different methods

In [11]:
np.random.seed()

D = np.random.random(10)*5
print(D)

# Mathode 1
print(D // 1)

# Methode 2
print(np.floor(D))

# Methode 3
print(np.ceil(D) - 1)

# Methode 4 : casting
print(D.astype('int8'))

# Mathode 5
print(D - D % 1)

# Method 6
print(np.trunc(D))


[0.13130415 2.24341752 4.47513435 1.00461334 0.03439394 3.93942651
 0.05107653 4.56733756 4.55761439 2.86259544]
[0. 2. 4. 1. 0. 3. 0. 4. 4. 2.]
[0. 2. 4. 1. 0. 3. 0. 4. 4. 2.]
[0. 2. 4. 1. 0. 3. 0. 4. 4. 2.]
[0 2 4 1 0 3 0 4 4 2]
[0. 2. 4. 1. 0. 3. 0. 4. 4. 2.]
[0. 2. 4. 1. 0. 3. 0. 4. 4. 2.]


### 37. Create a 5x5 matrix with row values ranging from 0 to 4

In [14]:
E = np.repeat(np.arange(5),5).reshape(5,5)
E.transpose()

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [15]:
F = np.repeat(np.arange(5),5).reshape(5,5)
np.rot90(F)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [16]:
G = np.zeros((5,5))
G += np.arange(5)
G

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [17]:
H = np.tile(np.arange(0,5),(5,1))
H

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

### 38. Consider a generator function that generates 10 integers and use it to build an array

In [18]:
np.random.randint(0,100,10)

array([ 9, 76, 86,  0, 91, 20, 83, 37, 24, 28])

In [21]:
def generate():
  for x in np.random.randint(1,100,10):
    yield x

I = np.fromiter(generate(),dtype=float,count=-1)
I

array([25., 23.,  8., 24., 28.,  3., 45., 43., 78., 59.])

### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [22]:
np.random.random(10)

array([0.95051727, 0.33889055, 0.48218989, 0.33388839, 0.79412105,
       0.13150379, 0.70737163, 0.99085656, 0.67426092, 0.06632106])

In [25]:
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

### 40. Create a random vector of size 10 and sort it

In [29]:
J = np.random.random(10)
print(np.sort(J))

[0.08201556 0.34361156 0.55331651 0.60648015 0.68693672 0.70641303
 0.82936094 0.87023341 0.91696424 0.96751822]


### 41. How to sum a smaller array faster than np.sum?

In [30]:
K = np.array([1,2,3,4])
np.add.reduce(K)

10

### 42. Consider two random array A and B, check if they are equal

In [31]:
L = np.array([0,1,2,3,4])
M = np.array([1,2,3,4,0])

np.array_equal(L,M)

False

### 43. Make an array immutable (read-only)

In [33]:
unchangable = np.array([1,2,3,4])
unchangable.flags.writeable = False
# unchangable[3] = 2

### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [ ]:
N = np.random.randint(0,10,(10,2))
'''
(x**2 + y**2) ** (1/2) = r
arctan(y/x) = theta
'''
r = np.sqrt(np.sum(np.power(N,2),axis=1))
theta = np.arctan(N[:,1]/N[:,0])
polar = np.concatenate((r,theta))
print(polar)

[7.         4.24264069 3.         9.21954446 6.         9.21954446
 8.06225775 9.48683298 7.81024968 7.61577311 1.57079633 0.78539816
 1.57079633 1.35212738 0.         1.35212738 1.44644133 0.32175055
 0.87605805 1.16590454]


C:\Users\TabotCharlesBessong\AppData\Local\Temp\ipykernel_5164\3436679282.py:7: RuntimeWarning: divide by zero encountered in divide
  theta = np.arctan(N[:,1]/N[:,0])


### 45. Create random vector of size 10 and replace the maximum value by 0

In [42]:
np.random.seed()

O = np.random.randint(1,10,(10,1))
print(O)
O[O.argmax()] = 0
print(O)

[[1]
 [3]
 [5]
 [3]
 [9]
 [3]
 [8]
 [6]
 [8]
 [2]]
[[1]
 [3]
 [5]
 [3]
 [0]
 [3]
 [8]
 [6]
 [8]
 [2]]


In [43]:
P = np.where(O == max,0,O)
P

array([[1],
       [3],
       [5],
       [3],
       [0],
       [3],
       [8],
       [6],
       [8],
       [2]])

### 46. Create a structured array with x and y coordinated covering the [0,1]x[0,1] area

In [44]:
# sorry i dont understand the problem, i guess i will not even understand the solution

In [46]:
P = np.zeros((5,5),[('x',float),('y',float)])
P['x'], P['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
P

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij = 1/(xi - yj))

In [47]:
Q = np.array([1,2,3,4])
R = np.array([8,9])

Cauchy = np.zeros((len(R),len(Q)))

for i in range(len(Q)):
  for j in range(len(R)):
    Cauchy[j,i] = 1 / (Q[i]-R[j])
    
    
Cauchy

array([[-0.14285714, -0.16666667, -0.2       , -0.25      ],
       [-0.125     , -0.14285714, -0.16666667, -0.2       ]])

In [50]:
S = np.arange(8)
T = S + 0.5
Cauchy1 = 1.0 / np.subtract.outer(S,T)
print(np.linalg.det(Cauchy1))
print(Cauchy1)

3638.1636371179666
[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]
