In [ ]:
hello = "Hello world"
print(hello)

In [3]:
list1 = ['a','b','d'] 

In [ ]:
import numpy as np
import pandas as pd 

list1 = ['a','b','d'] 
labels = [1,2,3]
ser1 = pd.Series(data=list1 , index = labels)
print(ser1)

: 

In [ ]:
import numpy as np
import pandas as pd 

list1 = ['a','b','d'] 
labels = [1,2,3]
ser1 = pd.Series(data=list1 , index = labels)
print(ser1)

ModuleNotFoundError: No module named 'numpy'

In [5]:
import numpy as np
import pandas as pd 

list1 = ['a','b','d'] 
labels = [1,2,3]
ser1 = pd.Series(data=list1 , index = labels)
print(ser1)

1    a
2    b
3    d
dtype: object


In [6]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [7]:
a[0]


1

In [ ]:
import time
import sys 


In [9]:
b = range(1000)
print(sys.getsizeof(5) * len(BytesWarning))

TypeError: object of type 'type' has no len()

In [11]:
b = range(1000)
print(sys.getsizeof(5) * len(b))

28000


In [ ]:
import time

In [13]:
c = np.arange(1000)
print(c.size*c.itemsize)

4000


In [ ]:
import time
size = 1000 
# L1 = range(size)
# L2 = range(size)b
A1 = np.arange(size)
A2 = np.arange(size)
start = time.time()
# res = [(x+y) for x,y in zip(L1,L2) ]
# res1 = [(x+y) for x,y in zip(A1,A2) ]
res1 = A1 + A2 
# print(res)
print(res1)
print("Python list took: ",(time.time() - start) * 1000 )

In [26]:
a = np.array([[1,2],[3,4],[5,6]]) 
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
a.ndim
a.itemsize
a.shape

(3, 2)

In [31]:
a = np.array([[1,2],[3,4],[5,6]] , dtype = np.float64 ) 
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [32]:
a.itemsize


8

In [33]:
a = np.array([[1,2],[3,4],[5,6]] , dtype = np.complex64 )
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]], dtype=complex64)

In [40]:
a = np.zeros((1,4))
a

array([[0., 0., 0., 0.]])

d = np.ones((3,4))
d

In [5]:
import numpy as np
e = np.array([(1, 2, 3), [4, 5, 6], (7, 8, 9)])
e 
e.dtype
e.dtype.name

'int32'

In [2]:
import numpy as np

np.random.random((3,5))

array([[0.59654193, 0.3299929 , 0.60605085, 0.29785315, 0.95176548],
       [0.86307169, 0.62385798, 0.34343181, 0.075568  , 0.41882069],
       [0.95091683, 0.4628553 , 0.01592013, 0.07484637, 0.60478122]])

In [3]:
g = np.ones((4,7))
g

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [5]:
A = np.arange(0,9).reshape(3,3)
A
B = np.ones((3,3))
B
A * B


array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [7]:
np.dot(A,B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [10]:
np.sqrt(A)



array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

In [12]:
np.log(B)


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.sin(A)

array([[ 0.        ,  0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825]])

In [15]:
h = np.arange(10,20)
h[[3,1,5]]

array([13, 11, 15])

In [18]:
i = np.arange(10,19).reshape((3,3))
i[2,0]

16

Slicing

It allows you to extract portion of an array

In [24]:
j = np.arange(2,10)
# This is almost same to list slcing
j[::2]
for i in j:
  print(i)

2
3
4
5
6
7
8
9


In [25]:
C = np.arange(0,20).reshape((4,5))
C[0,:]
for m in C:
  print(m)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [27]:
np.apply_along_axis(np.mean, axis=1, arr=A)

array([1., 4., 7.])

In [32]:
A = np.arange(10, 19).reshape((3, 3))

def foo(x):
  return x/2

np.apply_along_axis(foo,axis=1,arr=A)

array([[5. , 5.5, 6. ],
       [6.5, 7. , 7.5],
       [8. , 8.5, 9. ]])

In [51]:
A = np.random.random((4, 4))
A > 0.6 
# we use boolean for selection
A[A < 0.6]

array([0.07626042, 0.50562257, 0.03458034, 0.28996618, 0.23896524,
       0.04987434, 0.20176672])

In [52]:
a = np.random.random(12)

a

array([0.50901244, 0.87265004, 0.18452156, 0.90001373, 0.39085733,
       0.65891816, 0.8641736 , 0.09835987, 0.37581871, 0.41960112,
       0.1190189 , 0.52195771])

In [54]:
A = a.reshape(3,4)
A

array([[0.50901244, 0.87265004, 0.18452156, 0.90001373],
       [0.39085733, 0.65891816, 0.8641736 , 0.09835987],
       [0.37581871, 0.41960112, 0.1190189 , 0.52195771]])

In [56]:
D = A.ravel()
# The ravel function helps change a multi dimensional array to a uni dimensional array
D

array([0.50901244, 0.87265004, 0.18452156, 0.90001373, 0.39085733,
       0.65891816, 0.8641736 , 0.09835987, 0.37581871, 0.41960112,
       0.1190189 , 0.52195771])

Stackin , Joining arrays together

In [57]:
E = np.ones((3,3))
F = np.zeros((3,3))
np.vstack((E,F))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

We have vertical stacking which cmobines arrays vertically 
we have the horizontal stacking which cmobines arrays horizontally 

In [59]:
np.hstack((E,F))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

we also have stacking methose for one dimensional arrays 

In [60]:
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
c = np.array([6, 7, 8])
np.column_stack((a, b, c))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [61]:
np.row_stack((a,c,b))

array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

Sometimes , we will need to spilt arrays so as to divide it for easy analysis . And with some conditions , we get a particular data and renove it from others 
The default is the vertical spli

In [62]:
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [66]:
[G,H] = np.hsplit(A,2)
G

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [67]:
H

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [68]:
[A1,A2,A3] = np.split(A,[1,3],axis=0)
A1

array([[0, 1, 2, 3]])

In [69]:
A2

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
A3

array([[12, 13, 14, 15]])

In [72]:
C = A.copy()
A[0] = 0
C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])