In [ ]:
hello = "Hello world"
print(hello)

Hello world


In [3]:
list1 = ['a','b','d'] 

In [ ]:
import numpy as np
import pandas as pd 

list1 = ['a','b','d'] 
labels = [1,2,3]
ser1 = pd.Series(data=list1 , index = labels)
print(ser1)

: 

In [ ]:
import numpy as np
import pandas as pd 

list1 = ['a','b','d'] 
labels = [1,2,3]
ser1 = pd.Series(data=list1 , index = labels)
print(ser1)

ModuleNotFoundError: No module named 'numpy'

In [5]:
import numpy as np
import pandas as pd 

list1 = ['a','b','d'] 
labels = [1,2,3]
ser1 = pd.Series(data=list1 , index = labels)
print(ser1)

1    a
2    b
3    d
dtype: object


In [6]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [7]:
a[0]


1

In [ ]:
import time
import sys 


In [9]:
b = range(1000)
print(sys.getsizeof(5) * len(BytesWarning))

TypeError: object of type 'type' has no len()

In [11]:
b = range(1000)
print(sys.getsizeof(5) * len(b))

28000


In [ ]:
import time

In [13]:
c = np.arange(1000)
print(c.size*c.itemsize)

4000


In [ ]:
import time
size = 1000 
# L1 = range(size)
# L2 = range(size)b
A1 = np.arange(size)
A2 = np.arange(size)
start = time.time()
# res = [(x+y) for x,y in zip(L1,L2) ]
# res1 = [(x+y) for x,y in zip(A1,A2) ]
res1 = A1 + A2 
# print(res)
print(res1)
print("Python list took: ",(time.time() - start) * 1000 )

In [26]:
a = np.array([[1,2],[3,4],[5,6]]) 
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
a.ndim
a.itemsize
a.shape

(3, 2)

In [31]:
a = np.array([[1,2],[3,4],[5,6]] , dtype = np.float64 ) 
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [32]:
a.itemsize


8

In [33]:
a = np.array([[1,2],[3,4],[5,6]] , dtype = np.complex64 )
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]], dtype=complex64)

In [40]:
a = np.zeros((1,4))
a

array([[0., 0., 0., 0.]])

d = np.ones((3,4))
d

In [5]:
import numpy as np
e = np.array([(1, 2, 3), [4, 5, 6], (7, 8, 9)])
e 
e.dtype
e.dtype.name

'int32'

In [6]:
f = np.arange(0,12).reshape(3,4)
f

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
np.random.random((3,4))

array([[0.08693147, 0.58952232, 0.62325477, 0.76313306],
       [0.13791231, 0.93075387, 0.73847163, 0.6784235 ],
       [0.37287965, 0.89146074, 0.00493117, 0.9136914 ]])